### PR TITLE
Upgrade gjavah

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by pomadchin** [comment]
Thanks for your first contribution! 🎉 
Hmm, I'm wondering, can we make a direct dependecy on https://github.com/Glavo/gjavah?

**Comment by sideeffffect** [comment]
Unfortunately, [`gjavah` isn't published to Maven Central](https://search.maven.org/search?q=gjavah).
So I'd prefer to just "upgrade" it like this PR does.

**Comment by pomadchin** [comment]
@sideeffffect hmm got it, and https://jitpack.io doesn't work for you? 
But anyway I'm good to merge it as-is in order to avoid having a dependency to a an extra repo.

**Comment by sideeffffect** [comment]
jitpack.io is neat, but it's more of a hack. Many people rely on mirrors that include only Maven Central (and maybe few other prominent repositories), typically enterprises, etc...

**Comment by pomadchin** [comment]
Merging once CI is 🟢

**Pull request merged**
