### PR TITLE
Add Java 17 to CI

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by pomadchin** [comment]
Hm, how do you feel about dropping JDK8 builds / publish, leaving 11 and 17 only but with the set javac target to 1.8?

**Comment by sideeffffect** [comment]
I would feel really sad about that. The ability to run on mere 8 is Scala's strength and 8 is embraced by the whole Scala community as the "base" version of Java.
What's the downside of keeping 8 around? :slightly_smiling_face:

**Comment by pomadchin** [comment]
@sideeffffect the only downside is the CI runtime 🤷 but i'm okay with keeping it there. I still want to switch builds to jdk11 at least as the defatult.

**Review by pomadchin — APPROVED** [review]
🚀

**Comment by sideeffffect** [comment]
> switch builds to jdk11 at least as the default

What do you mean by that? :thinking:

**Comment by pomadchin** [comment]
@sideeffffect smth like this https://github.com/sbt/sbt-jni/pull/85

**Pull request merged**
